
### Register
POST  http://localhost:3000/signup
Content-Type: application/json

{
  "name":"Abdala El-Said",
  "email": "said@gmail.com",
  "password": "123456789"

}


### login
POST  http://localhost:3000/login
Content-Type: application/json
Authorization:  Bearer 

{
  "email": "shikabala@gmail.com",
  "password": "123456789"
}



### forget password
POST  http://localhost:3000/auth/reset-password
Content-Type: application/json

{
  "email": "hadyhashim17@gmail.com"
}



###verfication code 
POST  http://localhost:3000/auth/verify-code
Content-Type: application/json

{
  "code": "232418"
}


###reset password
POST  http://localhost:3000/auth/change-password
Content-Type: application/json

{
  "email": "hadyhashim17@gmail.com",
  "password": "123456789"
}



###Logout 
POST  http://localhost:3000/logout
Content-Type: application/json


###Logout 
GET   http://localhost:3000/test-cookie
Content-Type: application/json

